### ISSUE TITLE
Customize order of storage

### ISSUE THREAD

**Issue by larsha** [ripeworks/local-storage-fallback#11]
Hi,

Great package, I was wondering if you have though about making it possible to specify the order of storage? E.g now I'm working with https://github.com/IdentityModel/oidc-client-js and I would love to use the SessionStorage before the LocalStorage in a nice way. Maybe with some sort of initial config passed to a constructor or something to set it up.

If you don't have time, I can of course take a look and add a PR for you to have a look at.

**Comment by tamagokun** [comment]
Oh yeah, you can totally do this. You can use what's in `index.js` as a guide for doing it yourself. https://github.com/ripeworks/local-storage-fallback/blob/master/src/index.js

The `isSupported` helper and additional storage modules are all exported in the module.

e.g.

```js
// myStorage.js
import { isSupported, CookieStorage, MemoryStorage } from 'local-storage-fallback'

let storage = null

if (isSupported('sessionStorage')) {
  storage = window.sessionStorage
} else if (isSupported('localStorage')) {
  storage = window.localStorage
} else if (isSupported('cookieStorage')) {
  storage = new CookieStorage()
} else {
  storage = new MemoryStorage()
}

export default storage
```

**Comment by larsha** [comment]
Yeah I noticed that, will go with that way of doing it then. Thanks!
