### ISSUE TITLE
MemoryStorage getItem should return null instead of undefined if given key doesn't exists

### ISSUE THREAD

**Issue by DmitryFillo** [ripeworks/local-storage-fallback#13]
According to [spec](https://html.spec.whatwg.org/multipage/webstorage.html) local / session storages should return null for ``getItem(key)`` call if no given key, but fallback MemoryStorage returns undefined, which is inconstant behaviour, so if you doing ``JSON.parse(storage.getItem(key))`` you'll fail if only MemoryStorage is available.

**Comment by DmitryFillo** [comment]
PR https://github.com/ripeworks/local-storage-fallback/pull/14

**Comment by tamagokun** [comment]
:+1: released in `4.1.0` :tada:
