### ISSUE TITLE
Cross domain support?

### ISSUE THREAD

**Issue by tsanborn19-zz** [ripeworks/local-storage-fallback#15]
I am using this library, and have a requirement to support setting cross-domain storage items. For example, it is currently being set for sub1.domain.com, but is not set for sub2.domain.com. Is there a way to have it set for *.domain.com?

**Comment by tamagokun** [comment]
Can't be done, though you might be able to get away with using a cookie, depends on your storage needs:

If you set a cookie's domain to be `.domain.com` (leading dot), then it can be used across multiple subdomains, but not the top-level domain.

So, you could do something like this:

```js
import { CookieStorage } from 'local-storage-fallback'

const storage = new CookieStorage({domain: '.domain.com'})

// sub1.domain.com
storage.setItem('foo', 'bar')

// sub2.domain.com
storage.getItem('foo', 'bar')
```
