### ISSUE TITLE
Option to exclude CookieStorage

### ISSUE THREAD

**Issue by k-lekh** [ripeworks/local-storage-fallback#17]
First of all, many thanks for this library!

Since the CookieStorage has limits, it would be useful to have an option to exclude this storage from fallbacks.

**Comment by tamagokun** [comment]
sure, you can do that by setting up your own instance similar to what this library does here: https://github.com/ripeworks/local-storage-fallback/blob/master/src/index.js

```js
import { isSupported, MemoryStorage } from "local-storage-fallback";

let storage = null;

if (isSupported('localStorage')) {
  // use localStorage
  storage = window.localStorage;
} else if (isSupported('sessionStorage')) {
  // use sessionStorage
  storage = window.sessionStorage;
} else {
  // use memory
  storage = new MemoryStorage();
}

export default storage;
```
