### ISSUE TITLE
"window.localStorage = storage;" throws an error

### ISSUE THREAD

**Issue by gkorland** [ripeworks/local-storage-fallback#2]
In the README you show the following shim:

```
// Or shim window.localStorage
window.localStorage = storage;
```

But, browsers won't let you write on this readonly

**Comment by tamagokun** [comment]
Ah, correct. You need to check if localStorage exists in window before calling this. Something like this should work:

``` js
if (!('localStorage' in window)) {
  window.localStorage = storage;
}
```

**Comment by tamagokun** [comment]
closing this. Re-open if you are still having problems. Thanks!

**Comment by gkorland** [comment]
thanks
