### ISSUE TITLE
Upgrade to Cookie dependency to ^1.0

### ISSUE THREAD

**Issue by AJenbo** [ripeworks/local-storage-fallback#39]
Security issues where found in the older versions, since this package is locked to ^0.3.1 it's not automatically upgraded on the users end past the 2016 release.

See https://github.com/jshttp/cookie/releases for notes regarding upgrading to the 1.0 version of Cookie.

**Comment by tamagokun** [comment]
thanks for reporting. Going to work on a new version with the latest cookie version

**Comment by tamagokun** [comment]
released in `5.0.0` 🎉

**Comment by AJenbo** [comment]
Thank you <3
